config/routes.rb
Rails.application.routes.draw do

  resources :search_urls
  resources :search_sites 
  resources :search_categories
  resources :elements
  resources :whouses

  resources :layouts
  resources :layout_elements
  resources :whouse_elements
  resources :goods_search
  resources :note_search
  resources :usd

  resources :users

  root :to => "whouse_elements#index"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post "ajax/add_lay_el"
  post "ajax/del_lay_el"
  post "ajax/add_wh_el"
  post "ajax/del_wh_el"
  post "ajax/upd_param"
  get "ajax/check_status"

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit'

end

app/models/element.rb
class Element < ActiveRecord::Base
   has_many :layout_elements
   has_many :whouse_elements, dependent: :destroy
   has_many :layouts, through: :layout_elements
   has_many :whouses, through: :whouse_elements

  attr_accessor :parents_count
  
  def parents_count
    self.try(:layouts).count
  end

end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
    @element = Element.new

    @items  = Element.order(:name)  
    @item = Element.new

  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to '/options/elements', notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to '/options/elements', notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to '/options/elements', notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:name)
    end
end

app/views/elements/_elements.html.erb
<%= render("shared/simple_option") %>

app/views/elements/_form.html.erb
<%= simple_form_for(@element) do |f| %>

  <div class="form-inputs">
    <%= f.input :name,label: 'Новый элемент:' %>
    <span class="btn-sm btn-success left mrg_l">Добавить</span>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Редактирование</h1>

<%= render 'shared/name_edit_form',:model =>@element %>

app/views/elements/index.html.erb
<h3>Микросхемы и т.д.</h3>

<div class="panel panel-default">
<table class="table table-striped table-hover">

  <thead>
    <tr>
      <th>Наименование</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.name %></td>
         <%= edit_delete(element) %>
      </tr>
    <% end %>
      <tr>
        <td colspan="2"><%= render "form" %></td>
      </tr>

  </tbody>

</table>

<br>

<% link_to 'Добавить элемент', new_element_path, class: "btn btn-success" %>

</div>

app/views/elements/index.js.erb
$(".content").html("<%= escape_javascript(render("shared/simple_option")) %>");

app/views/elements/new.html.erb
<h1>Новый эелемент</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @element.name %>
</p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>