config/routes.rb
Rails.application.routes.draw do

  resources :search_urls
  resources :search_sites 
  resources :search_categories
  resources :elements
  resources :whouses

  resources :layouts
  resources :layout_elements
  resources :whouse_elements
  resources :goods_search
  resources :note_search
  resources :usd

  resources :users

  root :to => "whouse_elements#index"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post "ajax/add_lay_el"
  post "ajax/del_lay_el"
  post "ajax/add_wh_el"
  post "ajax/del_wh_el"
  post "ajax/upd_param"
  get "ajax/check_status"

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit'

end

app/models/search_category.rb
class SearchCategory < ActiveRecord::Base
  has_many :urls, class_name: "SearchUrl", foreign_key: :search_category_id
  def parents_count
    0
  end

end

app/controllers/search_categories_controller.rb
class SearchCategoriesController < ApplicationController
  before_action :set_search_category, only: [:show, :edit, :update, :destroy]

  # GET /search_categories
  # GET /search_categories.json
  def index
    @search_categories = SearchCategory.all
    @items = SearchCategory.order(:name)
    @item  = SearchCategory.new
  end

  # GET /search_categories/1
  # GET /search_categories/1.json
  def show
  end

  # GET /search_categories/new
  def new
    @search_category = SearchCategory.new
  end

  # GET /search_categories/1/edit
  def edit
  end

  # POST /search_categories
  # POST /search_categories.json
  def create
    @search_category = SearchCategory.new(search_category_params)

    respond_to do |format|
      if @search_category.save
        format.html { redirect_to @search_category, notice: 'Search category was successfully created.' }
        format.json { render :show, status: :created, location: @search_category }
      else
        format.html { render :new }
        format.json { render json: @search_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_categories/1
  # PATCH/PUT /search_categories/1.json
  def update
    respond_to do |format|
      if @search_category.update(search_category_params)
        format.html { redirect_to @search_category, notice: 'Search category was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_category }
      else
        format.html { render :edit }
        format.json { render json: @search_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_categories/1
  # DELETE /search_categories/1.json
  def destroy
    @search_category.destroy
    respond_to do |format|
      format.html { redirect_to search_categories_url, notice: 'Search category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_category
      @search_category = SearchCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_category_params
      params.require(:search_category).permit(:name)
    end
end

app/views/search_categories/_form.html.erb
<%= simple_form_for(@search_category) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/search_categories/_search_categories.html.erb
<%= render("shared/simple_option") %>

app/views/search_categories/edit.html.erb
<h1>Editing Search Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_category %> |
<%= link_to 'Back', search_categories_path %>

app/views/search_categories/index.html.erb
<h1>Listing Search Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_categories.each do |search_category| %>
      <tr>
        <td><%= search_category.name %></td>
        <td><%= link_to 'Show', search_category %></td>
        <td><%= link_to 'Edit', edit_search_category_path(search_category) %></td>
        <td><%= link_to 'Destroy', search_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search category', new_search_category_path %>

app/views/search_categories/index.js.erb
$(".content").html("<%= escape_javascript(render("shared/simple_option")) %>");

app/views/search_categories/new.html.erb
<h1>New Search Category</h1>

<%= render 'form' %>

<%= link_to 'Back', search_categories_path %>

app/views/search_categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @search_category.name %>
</p>

<%= link_to 'Edit', edit_search_category_path(@search_category) %> |
<%= link_to 'Back', search_categories_path %>