config/routes.rb
Rails.application.routes.draw do

  resources :search_urls
  resources :search_sites 
  resources :search_categories
  resources :elements
  resources :whouses

  resources :layouts
  resources :layout_elements
  resources :whouse_elements
  resources :goods_search
  resources :note_search
  resources :usd

  resources :users

  root :to => "whouse_elements#index"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post "ajax/add_lay_el"
  post "ajax/del_lay_el"
  post "ajax/add_wh_el"
  post "ajax/del_wh_el"
  post "ajax/upd_param"
  get "ajax/check_status"

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit'

end

app/models/search_url.rb
class SearchUrl < ActiveRecord::Base
  belongs_to :site, class_name: "SearchSite", foreign_key: :search_site_id
  belongs_to :category, class_name: "SearchCategory", foreign_key: :search_category_id


  def parents_count
    0
  end


end

app/controllers/search_urls_controller.rb
class SearchUrlsController < ApplicationController
  before_action :set_search_url, only: [:show, :edit, :update, :destroy]

  # GET /search_urls
  # GET /search_urls.json
  def index

    @search_urls = SearchUrl.order(:search_category_id)
    @categories = SearchCategory.order(:name)
    @sites = SearchSite.all

    @site = params[:url_sites]
    @cathegory = params[:url_category]    
    if params[:url_sites] && (params[:url_sites].to_i > 0)
      @search_urls = @search_urls.where(:site=>params[:url_sites])
    end
    if params[:url_category] && (params[:url_category].to_i > 0)
      @search_urls = @search_urls.where(:category=>params[:url_category])
    end

  end

  # GET /search_urls/1
  # GET /search_urls/1.json
  def show
  end

  # GET /search_urls/new
  def new
    @cathegory = params[:cat]
    @site = params[:site]
    @search_url = SearchUrl.new
    @sites = SearchSite.all
    @categories =SearchCategory.all
  end

  # GET /search_urls/1/edit
  def edit
    @sites = SearchSite.all
    @categories =SearchCategory.all
    @cathegory = @search_url.search_category_id
    @site = @search_url.search_site_id
  end

  # POST /search_urls
  # POST /search_urls.json
  def create
    @search_url = SearchUrl.new(search_url_params)

    respond_to do |format|
      if @search_url.save
        format.html { redirect_to search_urls_url, notice: 'Search url was successfully created.' }
        format.json { render :show, status: :created, location: @search_url }
      else
        format.html { render :new }
        format.json { render json: @search_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_urls/1
  # PATCH/PUT /search_urls/1.json
  def update
    respond_to do |format|
      if @search_url.update(search_url_params)
        format.html { redirect_to search_urls_url, notice: 'Search url was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_url }
      else
        format.html { render :edit }
        format.json { render json: @search_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_urls/1
  # DELETE /search_urls/1.json
  def destroy
    @search_url.destroy
    respond_to do |format|
      format.html { redirect_to search_urls_url, notice: 'Search url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_url
      @search_url = SearchUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_url_params
      params.require(:search_url).permit(:url, :search_site_id, :search_category_id, :disabled)
    end
end

app/views/search_urls/_form.html.erb
<%= simple_form_for(@search_url) do |f| %>

  <div class="form-inputs">
    
    
    <%= f.select :search_site_id, content_tag(:option,'Сайт...',:value=>nil)+options_for_select(@sites.collect{ |u| [u.name, u.id] }, @site) %>
    <%= f.select :search_category_id, content_tag(:option,'Категория...',:value=>nil)+options_for_select(@categories.collect{ |u| [u.name, u.id] }, @cathegory) %>
    <div class="right">

      <div class="inp_btn checkbox active"><%= f.check_box :disabled %></div><label>Отключить</label>
    </div>
    
    <%= f.text_area :url, :class => 'w80 margin_top_20'  %>
    <span class="copy">Copy</span>
    <% if !@search_url.site.nil? %>
      <%= link_to image_tag(@search_url.site.name+".ico"),@search_url.url, target:"_blank" %>
    <% end -%>

  </div>
  
</br>
  <div class="form-actions">
    <%= f.button :submit, "Записать", class: 'btn-success' %>
    <%= link_to 'Отмена', search_urls_path, :class => "sub btn_a btn_reset"%>
  </div>


<% end %>

app/views/search_urls/_urls.html.erb
<div class="panel panel-default">
      <div class="panel-heading table-heading"></div>
      <table class="table table-striped table-hover" model="<%= @search_urls.class.name %>">

  <thead>
    <tr>
      <th></th>
      <th>Url</th>
      
      <th width="150px;">Категория</th>
      <th></th>
      <th width="30px;"> </th>
    </tr>
  </thead>

  <tbody>
    <% @search_urls.each do |search_url| %>
      <tr>
        <td><%= link_to image_tag(search_url.site.name+".ico"),search_url.url, target:"_blank" %></td>
        <td><%= short_name(search_url.url) %></td>

        <td><%= search_url.category.name %></td>
        <td><%= search_url.disabled %></td>
        <%= td_edit_delete(search_url) %>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/search_urls/edit.html.erb
<h3>Редактирование адреса поиска:</h3>

<%= render 'form' %>

app/views/search_urls/index.html.erb
<h3>Адреса для поиска:</h3>

<div class="items_box_head">
<%= form_tag whouses_path, :method => 'get', :id => "url_search" do %>
  <div class="input-group left"> 
      <%= select_tag "url_sites", content_tag(:option,'Сайт...',:value=>0)+options_from_collection_for_select(@sites, "id", "name", @site), {:class => 'select'} %> 
      <%= select_tag "url_category", content_tag(:option,'Категория...',:value=>0)+options_from_collection_for_select(@categories, "id", "name",@cathegory), {:class => 'select'} %> 
      
  </div>
<% end %>
<%= link_to 'Новый адрес', new_search_url_path(cat: params[:url_category], site: params[:url_sites]), class: "h25 btn btn-success btn-min right" %>
</div>


<div class="urls">
  <%= render "urls" %>
</div>

app/views/search_urls/index.js.erb
$(".urls").html("<%= escape_javascript(render("urls")) %>");

app/views/search_urls/new.html.erb
<h1>Новый адреса поиска:</h1>

<%= render 'form' %>

app/views/search_urls/show.html.erb
<p>
  <strong>Url:</strong>
  <%= @search_url.url %>
</p>

<p>
  <strong>Search site:</strong>
  <%= @search_url.search_site_id %>
</p>

<p>
  <strong>Search category:</strong>
  <%= @search_url.search_category_id %>
</p>

<%= link_to 'Edit', edit_search_url_path(@search_url) %> |
<%= link_to 'Back', search_urls_path %>