config/routes.rb
Rails.application.routes.draw do

  resources :search_urls
  resources :search_sites 
  resources :search_categories
  resources :elements
  resources :whouses

  resources :layouts
  resources :layout_elements
  resources :whouse_elements
  resources :goods_search
  resources :note_search
  resources :usd

  resources :users

  root :to => "whouse_elements#index"

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'                                   
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post "ajax/add_lay_el"
  post "ajax/del_lay_el"
  post "ajax/add_wh_el"
  post "ajax/del_wh_el"
  post "ajax/upd_param"
  get "ajax/check_status"

  get    'options'  => 'options#edit'
  get    'options/:options_page'  => 'options#edit'

end

app/models/search_site.rb
class SearchSite < ActiveRecord::Base
  def parents_count
    0
  end

end

app/controllers/search_sites_controller.rb
class SearchSitesController < ApplicationController
  before_action :set_search_site, only: [:show, :edit, :update, :destroy]
  before_action :set_arr, only: [:new,:edit]

  # GET /search_sites
  # GET /search_sites.json
  def index
    @search_sites = SearchSite.all
    @items  = SearchSite.order(:name)
    @item   = SearchSite.new
  end

  # GET /search_sites/1
  # GET /search_sites/1.json
  def show
    
  end

  # GET /search_sites/new
  def new
    @search_site = SearchSite.new
  end

  # GET /search_sites/1/edit
  def edit
  end

  # POST /search_sites
  # POST /search_sites.json
  def create
    @search_site = SearchSite.new(search_site_params)

    respond_to do |format|
      if @search_site.save
        format.html { redirect_to search_sites_url, notice: 'Search site was successfully created.' }
        format.json { render :show, status: :created, location: @search_site }
      else
        format.html { render :new }
        format.json { render json: @search_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_sites/1
  # PATCH/PUT /search_sites/1.json
  def update
    respond_to do |format|
      if @search_site.update(search_site_params)
        format.html { redirect_to search_sites_url, notice: 'Search site was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_site }
      else
        format.html { render :edit }
        format.json { render json: @search_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_sites/1
  # DELETE /search_sites/1.json
  def destroy
    @search_site.destroy
    respond_to do |format|
      format.html { redirect_to search_sites_url, notice: 'Search site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_site
      @search_site = SearchSite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_site_params
      params.require(:search_site).permit(:name,:items,:id_method,:id_field,:id_split,:title,:link_pref,:detail,:href,:price,:cookie,:warranty_css,:warranty_method,:warranty_split, :disabled)
    end

    def set_arr
      @wr_arr = {'На отдельной странице' => 'page','После разделителя' => 'split', 'Последний элемент' => 'last'}
      @id_arr = {'В ссылке' => 'link', 'В стиле' => 'css', 'Аттрибут с разделителем' => 'field', 'Аттрибут названия' => 'title' }
    end
end

app/views/search_sites/_form.html.erb
<%= simple_form_for(@search_site) do |f| %>

<div class="panel panel-default">
<div class="panel-heading table-heading"><label>Свойства разбора сайта:</label> <%= f.input :name, label: false %></div>

<table class="table table-striped table-hover" model="<%= @search_urls.class.name %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>css/field</th>
      <th>Method</th>
      <th>split</th>
    </tr>
  </thead>
  <tbody>
  	<tr><td>items</td><td><%= f.input :items, label: false %></td><td>disabled</td><td><%= f.input :disabled, label: false %></td></tr>
  	<tr><td>id</td><td><%= f.input :id_field, label: false %></td><td><%= f.select :id_method,options_for_select(@id_arr,@search_site.id_method) %></td>
        <td><%= f.input :id_split, label: false %></td></tr>
  	<tr><td>title</td><td><%= f.input :title, label: false %></td><td><%= f.input :title_field, label: false %></td><td></td></tr>
  	<tr><td>href</td><td><%= f.input :href, label: false %></td><td>link_pref</td><td><%= f.input :link_pref, label: false %></td></tr>
  	<tr><td>detail</td><td><%= f.input :detail, label: false %></td><td>cookie</td><td><%= f.input :cookie, label: false %></td></tr>
  	
  	<tr><td>price</td><td><%= f.input :price, label: false %></td><td></td><td></td></tr>
  	<tr><td>warranty</td><td><%= f.input :warranty_css, label: false %></td><td><%= f.select :warranty_method,options_for_select(@wr_arr,@search_site.warranty_method) %></td><td><%= f.input :warranty_split, label: false %></td></tr>
  </tbody>
  </table>
</div>

  <div class="form-actions">
    <%= f.button :submit, "Записать", class: 'btn-success' %>
    <%= link_to 'Отмена', search_sites_path, :class => "sub btn_a btn_reset"%>
  </div>
<% end  %>

app/views/search_sites/_search_sites.html.erb
<%= render("shared/simple_option") %>

app/views/search_sites/edit.html.erb
<h2>Редактирование</h2>

<%= render 'form' %>

app/views/search_sites/index.html.erb
<div class="panel panel-default">
      <div class="panel-heading table-heading"></div>
      <table class="table table-striped table-hover" model="<%= @search_urls.class.name %>">

  <thead>
    <tr>
      <th>Name</th>
      <th>Items</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_sites.each do |search_site| %>
      <tr>
        <td><%= search_site.name %></td>
        <td><%= search_site.items %></td>
	      <%= td_edit_delete(search_site) %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Добавить', new_search_site_path , class: 'btn-success'%>

app/views/search_sites/index.js.erb
$(".content").html("<%= escape_javascript(render("shared/simple_option")) %>");

app/views/search_sites/new.html.erb
<h1>New Search Site</h1>

<%= render 'form' %>

app/views/search_sites/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @search_site.name %>
</p>

<%= link_to 'Edit', edit_search_site_path(@search_site) %> |
<%= link_to 'Back', search_sites_path %>